### ISSUE TITLE
A nomad jobspec provided as JSON results in a panic when the jobspec does not contain an ID property

### ISSUE THREAD

**Issue by rcousens** [hashicorp/terraform-provider-nomad#302]
```
locals {
  NOMAD_JOB = {
    Job = {
      Name = "test"
      ....
    }
  }
}

resource "nomad_job" "nomad-spring" {
  jobspec = jsonencode(local.NOMAD_JOB)
  detach  = var.detach_immediately
  json    = true
}
```
### Debug Output
[Gist with debug output](https://gist.github.com/rcousens/545c7d12784704599be55628f00b056a)

### Panic Output
See Gist with debug output

### Expected Behavior
Nomad should have invalidated the jobspec and complained about a missing ID field

### Actual Behavior
Provider crashed

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `Define a jobspec without an ID property`

### Important Factoids
The crash comes from here: [nomad API client](https://github.com/hashicorp/nomad/blame/v1.3.8/api/jobs.go#L417)

Because job.ID is escaped and passed as a pointer, the failure to validate the spec contains an "ID" property causes a crash with a nil pointer dereference

### References
[Source of crash](https://github.com/hashicorp/terraform-provider-nomad/blob/v1.4.19/nomad/resource_job.go#L643)

**Comment by lgfa29** [comment]
Thanks for the report @rcousens!

This is actually a bug in the Nomad API client, where a `nil` check is missing before we get here:
https://github.com/hashicorp/nomad/blob/da9ec8ce1eb535bad83e8b9b9ea68e2c1886a8ee/api/jobs.go#L461

I was able to reproduce this by using a sample JSON file like this:
<details>
<summary> JSON job</summary>

```json
{
    "Job": {
        "Affinities": null,
        "AllAtOnce": false,
        "Constraints": null,
        "ConsulNamespace": "",
        "ConsulToken": "",
        "CreateIndex": 14,
        "Datacenters": [
            "dc1"
        ],
        "DispatchIdempotencyToken": "",
        "Dispatched": false,
        "JobModifyIndex": 14,
        "Meta": null,
        "Migrate": null,
        "ModifyIndex": 14,
        "Multiregion": null,
        "Name": "foo",
        "Namespace": "default",
        "NodePool": "default",
        "NomadTokenID": "",
        "ParameterizedJob": null,
        "ParentID": "",
        "Payload": null,
        "Periodic": null,
        "Priority": 50,
        "Region": "global",
        "Reschedule": null,
        "Spreads": null,
        "Stable": false,
        "Status": "pending",
        "StatusDescription": "",
        "Stop": false,
        "SubmitTime": 1685759953739812000,
        "TaskGroups": [
            {
                "Affinities": null,
                "Constraints": [
                    {
                        "LTarget": "${attr.consul.version}",
                        "Operand": "semver",
                        "RTarget": ">= 1.7.0"
                    }
                ],
                "Consul": {
                    "Namespace": ""
                },
                "Count": 1,
                "EphemeralDisk": {
                    "Migrate": false,
                    "SizeMB": 300,
                    "Sticky": false
                },
                "MaxClientDisconnect": null,
                "Meta": null,
                "Migrate": {
                    "HealthCheck": "checks",
                    "HealthyDeadline": 300000000000,
                    "MaxParallel": 1,
                    "MinHealthyTime": 10000000000
                },
                "Name": "foo",
                "Networks": null,
                "ReschedulePolicy": {
                    "Attempts": 0,
                    "Delay": 30000000000,
                    "DelayFunction": "exponential",
                    "Interval": 0,
                    "MaxDelay": 3600000000000,
                    "Unlimited": true
                },
                "RestartPolicy": {
                    "Attempts": 2,
                    "Delay": 15000000000,
                    "Interval": 1800000000000,
                    "Mode": "fail"
                },
                "Scaling": null,
                "Services": [
                    {
                        "Address": "192.168.1.2",
                        "AddressMode": "auto",
                        "CanaryMeta": null,
                        "CanaryTags": null,
                        "CheckRestart": null,
                        "Checks": null,
                        "Connect": null,
                        "EnableTagOverride": false,
                        "Meta": null,
                        "Name": "test",
                        "OnUpdate": "require_healthy",
                        "PortLabel": "mysql",
                        "Provider": "consul",
                        "TaggedAddresses": null,
                        "Tags": null,
                        "TaskName": ""
                    }
                ],
                "ShutdownDelay": null,
                "Spreads": null,
                "StopAfterClientDisconnect": null,
                "Tasks": [
                    {
                        "Affinities": null,
                        "Artifacts": null,
                        "Config": {
                            "args": [
                                "1"
                            ],
                            "command": "/bin/sleep"
                        },
                        "Constraints": null,
                        "DispatchPayload": null,
                        "Driver": "raw_exec",
                        "Env": null,
                        "Identity": null,
                        "KillSignal": "",
                        "KillTimeout": 5000000000,
                        "Kind": "",
                        "Leader": false,
                        "Lifecycle": null,
                        "LogConfig": {
                            "Disabled": false,
                            "Enabled": null,
                            "MaxFileSizeMB": 10,
                            "MaxFiles": 3
                        },
                        "Meta": null,
                        "Name": "foo",
                        "Resources": {
                            "CPU": 20,
                            "Cores": 0,
                            "Devices": null,
                            "DiskMB": 0,
                            "IOPS": 0,
                            "MemoryMB": 10,
                            "MemoryMaxMB": 0,
                            "Networks": null
                        },
                        "RestartPolicy": {
                            "Attempts": 2,
                            "Delay": 15000000000,
                            "Interval": 1800000000000,
                            "Mode": "fail"
                        },
                        "ScalingPolicies": null,
                        "Services": null,
                        "ShutdownDelay": 0,
                        "Templates": null,
                        "User": "",
                        "Vault": null,
                        "VolumeMounts": null
                    }
                ],
                "Update": {
                    "AutoPromote": false,
                    "AutoRevert": false,
                    "Canary": 0,
                    "HealthCheck": "checks",
                    "HealthyDeadline": 300000000000,
                    "MaxParallel": 1,
                    "MinHealthyTime": 10000000000,
                    "ProgressDeadline": 600000000000,
                    "Stagger": 30000000000
                },
                "Volumes": null
            }
        ],
        "Type": "service",
        "Update": {
            "AutoPromote": false,
            "AutoRevert": false,
            "Canary": 0,
            "HealthCheck": "",
            "HealthyDeadline": 0,
            "MaxParallel": 1,
            "MinHealthyTime": 0,
            "ProgressDeadline": 0,
            "Stagger": 30000000000
        },
        "VaultNamespace": "",
        "VaultToken": "",
        "Version": 0
    }
}
```
</details>

And running `nomad job plan -json job.json`, which results in this panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1009e1f68]

goroutine 1 [running]:
github.com/hashicorp/nomad/api.(*Jobs).PlanOpts(0x14000d1fc58, 0x14000643860, 0x14000d1fbbe, 0x101ce2235?)
        github.com/hashicorp/nomad/api@v0.0.0-20221006174558-2aa7e66bdb52/jobs.go:438 +0x98
github.com/hashicorp/nomad/command.(*JobPlanCommand).Run(0x1400040e600, {0x1400010e080, 0x2, 0x2})
        github.com/hashicorp/nomad/command/job_plan.go:250 +0x718
github.com/mitchellh/cli.(*CLI).Run(0x14000bee000)
        github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x4a8
main.Run({0x1400010e060, 0x4, 0x4})
        github.com/hashicorp/nomad/main.go:107 +0x29c
main.main()
        github.com/hashicorp/nomad/main.go:77 +0x50
```

Since this is an issue with Nomad I will move this to the `hashicorp/nomad` repo.

Thanks again for the report!
