### ISSUE TITLE
volumes: panic when using volumes data source

### ISSUE THREAD

**Issue by gokulasanthiya29** [hashicorp/terraform-provider-nomad#322]
CSI plugin for nomad crashed for all terraform versions, while trying to implement a pluggable volumes layer with portworx as the storage provider.

### Reference Code
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.50"
    }
    nomad = {
      source  = "hashicorp/nomad"
      version = "~> 1"
    }
    template = {
      source  = "hashicorp/template"
      version = "~> 2"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4"
    }
  }
  required_version = ">= 1.0"
}

provider "nomad" {
  address   = "https://nomad.dev.net:4646"
  secret_id = "secret-id"
  region    = "aws-us-east-1"
}

data "nomad_volumes" "example" {
  type      = "csi"
  plugin_id = "portworx"
}

output "inspected_volumes" {
  value = data.nomad_volumes.example.volumes
}
```

### Terraform's Panic Log
[](https://github.com/gokulasanthiya29/csi_plugin_crash/blob/master/crash.log)

The plugin on proper response should list the available CSI volumes. But on the contrary, the plugin did not respond.

This issue was encountered while generating terraform plan.
`terraform plan`

**Comment by jrasell** [comment]
The panic stack:
```
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: panic: assignment to entry in nil map
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: 
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: goroutine 51 [running]:
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: github.com/hashicorp/terraform-provider-nomad/nomad.volumesDataSourceRead(0xc000324bd0?, {0x114cb60?, 0xc000414de0?})
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: 	github.com/hashicorp/terraform-provider-nomad/nomad/data_source_volumes.go:74 +0x205
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc0003606e0, 0xc000324510?, {0x114cb60, 0xc000414de0})
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: 	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:413 +0x66
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc0001f2d00, 0xc000569990, 0x107f000?)
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: 	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:451 +0x65
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc0001270a8, {0xc00055c600?, 0x4bc346?}, 0xc00055c600)
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: 	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:1046 +0x2e9
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler({0x11b7ce0?, 0xc0001270a8}, {0x1587ab0, 0xc00089f6b0}, 0xc000825030, 0x0)
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: 	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3341 +0x170
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001c0000, {0x158d100, 0xc00054a820}, 0xc000309b00, 0xc00037bb90, 0x1d0b490, 0x0)
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: 	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: google.golang.org/grpc.(*Server).handleStream(0xc0001c0000, {0x158d100, 0xc00054a820}, 0xc000309b00, 0x0)
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: 	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2()
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: 	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2023-04-27T11:57:33.838+0530 [DEBUG] provider.terraform-provider-nomad_v1.4.20_x5: 	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
```

**Comment by gokulasanthiya29** [comment]
Hi @jrasell any new updates on this issue?
